# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2a542902ab21d3c744f99059df994cc2b2260e4b3e9966adf77a821d80d8f51aa91baa7bc19a295e373bd3c19d1fa18058a5b84f124e97e06b4d892a7f77db0

test:
  secret_key_base: a622ed0300c8af86a546571e6997a50d04818cb65fcebc6f251dbcb3d096e71fef961456599c383b0c636ee40c102ba4ff43fd1ae314f4cd7133deb2ec23e519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
